#!/bin/bash

# 1 core available on Travis CI OS X workers: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
# CPU_COUNT is passed through conda build: https://github.com/conda/conda-build/pull/1149
export CPU_COUNT=1

export PYTHONUNBUFFERED=1

export MACOSX_DEPLOYMENT_TARGET="10.9"

conda config --set show_channel_urls true
conda config --set add_pip_as_python_dependency false

conda update -n root --yes --quiet conda conda-env conda-build
conda install -n root --yes --quiet jinja2 conda-build anaconda-client

conda info
conda config --get
