#!/bin/bash

# 1 core available on Travis CI OS X workers: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
# MAKEFLAGS is passed through conda build: https://github.com/conda/conda-build/pull/917
export MAKEFLAGS="-j1 ${MAKEFLAGS}"

export PYTHONUNBUFFERED=1

conda config --set show_channel_urls true
conda config --set add_pip_as_python_dependency false

conda update -n root --yes --quiet conda
conda install -n root --yes --quiet jinja2 conda-build anaconda-client

conda info
conda config --get
